//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Dbopeartions
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpFileDetails
    {
        public int EmpId { get; set; }
        public string FilepathEmirates { get; set; }
        public string FilepathPassport { get; set; }
        public string FilepathCertificate { get; set; }
        public string FilepathResume { get; set; }
        public string emirates { get; set; }
        public string passport { get; set; }
        public string certificate { get; set; }
        public string resume { get; set; }
    }
}
